spring:
  application:
    name: student-service
# uncomment this for postgres db testing
#  datasource:
#    url: jdbc:postgresql://database-1.cit86seqme0a.us-east-1.rds.amazonaws.com:5432/studentdb
#    username: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver

#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true

server:
  port: 8089

cloud:
  aws:
    credentials:
       access-key: ${AWS_ACCESS_KEY:your-access-key}
       secret-key: ${AWS_SECRET_KEY:your-secret-key}
    region:
      static: ${AWS_REGION:us-east-1}

aws:
  bucket:
    name: s3-reenas-bucket

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#    register-with-eureka: true
#    fetch-registry: true


management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always

#resilience4j:
#  circuitbreaker:
#    instances:
#      schoolServiceBreaker:
#        registerHealthIndicator: true
#        eventConsumerBufferSize: 10
#        failureRateThreshold: 50
#        minimumNumberOfCalls: 5
#        automaticTransitionFromOpenToHalfOpenEnabled: true
#        waitDurationInOpenState: 6s
#        permittedNumberOfCallsInHalfOpenState: 3
#        slidingWindowSize: 10
#        slidingWindowType: COUNT_BASED
#  retry:
#    instances:
#      schoolServiceBreaker:
#        max-attempts: 3
#        wait-duration: 5s
#  ratelimiter: # Move this to the same level as circuitbreaker and retry
#    instances:
#      studentRateLimiter:
#        limit-for-period: 2
#        limit-refresh-period: 10s
#        timeout-duration: 1s

