cloud.aws.credentials.access-key=AKIA6LMZD5S6VGZAXH4P
cloud.aws.credentials.secret-key=secret-key
#if you have s3 bucket in ap-south change region while testing east is for dynamodb
cloud.aws.region.static=us-east-1

aws.bucket.name=reena-demo-bucket